# Generated by Django 2.2.28 on 2023-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_cbnf_sghty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asdt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvdb', models.BigIntegerField()),
                ('rurur', models.BigIntegerField()),
                ('wewrw', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='sghty',
            name='rel_asdt_n_n',
            field=models.ManyToManyField(blank=True, related_name='sghty_rel_asdt_n_n', to='home.Asdt'),
        ),
    ]
